backend:
  name: github
  repo: roberttivo29-sys/verifica-la-paz
  branch: main
  auth_scope: repo
  oauth:
    client_id: POv23li5VARzweAOk7S93
    client_secret: 8d7e52cdd485881ad521ab55da791e2c853ab3dd

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "proveedores"
    label: "Proveedores"
    folder: "data"
    create: true
    slug: "proveedores"
    extension: "json"
    format: "json"
    identifier_field: "id"
    fields:
      - { label: "ID (Número único)", name: "id", widget: "number" }
      - { label: "Nombre del Proveedor", name: "nombre", widget: "string" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Salud", "Hogar", "Automotriz", "Tecnologia", "Funeraria"] }
      - { label: "Subcategoría", name: "subcategoria", widget: "string" }
      - { label: "Dirección", name: "direccion", widget: "string", required: false }
      - { label: "Teléfono", name: "telefono", widget: "string", required: false }
      - { label: "WhatsApp (solo números)", name: "whatsapp", widget: "string", required: false }
      - { label: "Horario", name: "horario", widget: "string", required: false }
      - { label: "Rango de Precios", name: "precios", widget: "string", required: false }
      - { label: "Descripción", name: "descripcion", widget: "text", required: false }
      - { label: "Plan", name: "tipo_plan", widget: "select", options: ["gratuito", "premium", "ultra_premium"], default: "gratuito" }
      - { label: "¿Destacado en Portada?", name: "destacado", widget: "number", default: 0, hint: "1 = Sí, 0 = No" }
      - { label: "Link de Video (YouTube Embed)", name: "video_url", widget: "string", required: false, hint: "Ej: https://www.youtube.com/embed/CODIGO" }
      - { label: "Link de Audio", name: "audio_url", widget: "string", required: false }